<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="FreeImage.Standard" Version="4.3.8" />
    <PackageReference Include="Imageflow.AllPlatforms" Version="0.15.1" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.9" />
    <PackageReference Include="Microsoft.Maui.Graphics" Version="10.0.80" />
    <PackageReference Include="NetVips" Version="3.2.0" />
    <PackageReference Include="NetVips.Native.win-x64" Version="8.18.3" />
    <PackageReference Include="PhotoSauce.MagicScaler" Version="0.15.0" />
    <PackageReference Include="PhotoSauce.NativeCodecs.Libwebp" Version="1.4.0-preview1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SkiaSharp" Version="4.148.0" />
    <PackageReference Include="SkiaSharp.Views.Desktop.Common" Version="4.148.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
  </ItemGroup>

</Project>
